<?php

return [
    'support' => 'Support center',

    'login' => [
        'title' => 'Login to Continue',
        'username-or-email' => 'Username or Email',
        'password' => 'Password',
        'forgot-password' => 'Forgot password?',
        'login' => 'Login',

        'must-be-provided' => 'A username or email must be provided.',
        'please-enter-password' => 'Please enter your account password',

        'new-here' => 'New here? Create an account.',
    ],

    'forgot' => [
        'title' => 'Request Password Reset',
        'email' => 'Email',
        'email-description' => 'Enter your account email address to receive instructions on resetting your password.',
        'send-email' => 'Send Email',
        'return-to-login' => 'Return to Login',

        'a-valid-email-provided' => 'A valid email address must be provided to continue.',
    ],

    'device' => [
        'title' => 'Device Checkpoint',
        'recovery-code' => 'Recovery Code',
        'authentication-code' => 'Authentication Code',

        'continue' => 'Continue',

        'lost-device' => 'I\'ve Lost My Device',
        'have-device' => 'I Have My Device',

        'return-to-login' => 'Return to Login',

        'enter-one-of-recovery-codes' => 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.',
        'enter-two-factor' => 'Enter the two-factor token generated by your device',
    ],

    'reset' => [
        'title' => 'Reset Password',

        'email' => 'Email',
        'password' => 'Password',
        'confirm-password' => 'Confirm New Password',

        'return-to-login' => 'Return to Login',
        
        'password-required' => 'A new password is required.',
        'at-least-8-characters' => 'Your new password should be at least 8 characters in length.',
        'password-does-not-match' => 'Your new password does not match.',
    ],

    'register' => [
        'title' => 'Create an SKA Account',
        'username' => 'Username',
        'firstname' => 'First Name',
        'lastname' => 'Last Name',
        'email' => 'Email',
        'password' => 'Password',
        'confirm-password' => 'Confirm Password',
        'register' => 'Register',

        'already-have-account' => 'Already have an account?',

        'username-required' => 'A username is required.',
        'email-required' => 'An email address is required.',
        'valid-email-required' => 'A valid email address is required.',
        'firstname-required' => 'A first name is required.',
        'lastname-required' => 'A last name is required.',
        'password-required' => 'A password is required.',
        'confirm-password-required' => 'Please confirm your password.',
        'password-min-length' => 'Your password must be at least 8 characters.',
        'passwords-do-not-match' => 'The passwords do not match.',

        'valid-username-required' => 'A valid username is required (3-16 characters, letters, numbers, dashes and underscores only).',
        'username-taken' => 'The provided username is already in use.',

        'success-message' => 'You have successfully registered, check your email',
    ],
];